### ISSUE TITLE
Trebalo bi da nastavimo ovo

### ISSUE THREAD

**Issue by ThisIsPopka** [dsnkostic/iksoks#1]
Mislim da bi trebalo da nastavimo sa programiranjem **XO**. Bice to jedna originalna i inovativna aplikacija. Postacemo milioneri. *LOL*

[link youtube tutorial for github](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=1)

![2000px-Tic_tac_toe svg](https://user-images.githubusercontent.com/49984760/56744197-561d2d80-6778-11e9-95c9-b25c42d4f1df.png)

**Comment by dsnkostic** [comment]
I to ne sumnjam da postajemo milioneri :D

**Comment by ThisIsPopka** [comment]
Drago mi je da se slazes. Zatvaram issue. :D

**Comment by ThisIsPopka** [comment]
Moze i da se otvori ponovo ***LOL***
